version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 12
        commands:
            - 'npm install'
    pre_build:
        commands:
            - 'npm ci --production'
    build:
        commands:
            - 'npm run-script build'
artifacts:
    base-directory: public
    files:
        - '**/*'
    discard-paths: no
cache:
    paths:
        - '.cache/*'
        - 'public/*'